name: tensorflow_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd77b12b_0
  - aiofiles=22.1.0=py38haa95532_0
  - aiohttp=3.8.5=py38h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aiosqlite=0.18.0=py38haa95532_0
  - anyio=3.5.0=py38haa95532_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py38haa95532_0
  - attrs=22.1.0=py38haa95532_0
  - babel=2.11.0=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py38haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py38haa95532_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2023.12.12=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cffi=1.15.1=py38h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.1.2=py38haa95532_0
  - contourpy=1.0.5=py38h59b6b97_0
  - cryptography=41.0.3=py38h3438e0d_0
  - cython=3.0.6=py38h2bbff1b_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py38h2bbff1b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - google-auth=2.22.0=py38haa95532_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=hf108199_0
  - grpcio=1.48.2=py38hf108199_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdf5=1.12.1=h51c971a_3
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.25.0=py38h9909e9c_0
  - ipython=8.12.2=py38haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py38haa95532_0
  - jedi=0.18.1=py38haa95532_1
  - jinja2=3.1.2=py38haa95532_0
  - joblib=1.2.0=py38haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py38haa95532_0
  - jupyter=1.0.0=py38haa95532_8
  - jupyter_client=7.4.9=py38haa95532_0
  - jupyter_console=6.6.3=py38haa95532_0
  - jupyter_core=5.3.0=py38haa95532_0
  - jupyter_events=0.6.3=py38haa95532_0
  - jupyter_server=1.23.4=py38haa95532_0
  - jupyter_server_fileid=0.9.0=py38haa95532_0
  - jupyter_server_ydoc=0.8.0=py38haa95532_1
  - jupyter_ydoc=0.2.4=py38haa95532_0
  - jupyterlab=3.6.3=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py38haa95532_0
  - jupyterlab_widgets=3.0.5=py38haa95532_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py38hd77b12b_0
  - krb5=1.19.4=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcurl=8.2.1=h86230a5_0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.16=h2bbff1b_2
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=hcd4344a_2
  - libtiff=4.5.1=hd77b12b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_1
  - libxslt=1.1.37=h2bbff1b_1
  - lxml=4.9.3=py38h09808a7_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.1=py38haa95532_0
  - markupsafe=2.1.1=py38h2bbff1b_0
  - matplotlib=3.7.2=py38haa95532_0
  - matplotlib-base=3.7.2=py38h4ed8f06_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mistune=0.8.4=py38he774522_1000
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - multidict=6.0.2=py38h2bbff1b_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py38haa95532_0
  - nbclient=0.5.13=py38haa95532_0
  - nbconvert=6.5.4=py38haa95532_0
  - nbformat=5.9.2=py38haa95532_0
  - nest-asyncio=1.5.6=py38haa95532_0
  - notebook=6.5.4=py38haa95532_1
  - notebook-shim=0.2.2=py38haa95532_0
  - oauthlib=3.2.2=py38haa95532_0
  - openssl=1.1.1w=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.1=py38haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.2.1=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=py38haa95532_0
  - platformdirs=3.10.0=py38haa95532_0
  - ply=3.11=py38_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py38haa95532_0
  - prompt-toolkit=3.0.36=py38haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycocotools=2.0.6=py38hbaf524b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38haa95532_1
  - pyjwt=2.4.0=py38haa95532_0
  - pyopenssl=23.2.0=py38haa95532_0
  - pyparsing=3.0.9=py38haa95532_0
  - pyqt=5.15.7=py38hd77b12b_0
  - pyqt5-sip=12.11.0=py38hd77b12b_0
  - pyrsistent=0.18.0=py38h196d8e1_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.18=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38haa95532_0
  - python-json-logger=2.0.7=py38haa95532_0
  - python_abi=3.8=2_cp38
  - pytz=2023.3.post1=py38haa95532_0
  - pywin32=305=py38h2bbff1b_0
  - pywinpty=2.0.10=py38h5da7b33_0
  - pyyaml=6.0=py38h2bbff1b_1
  - pyzmq=23.2.0=py38hd77b12b_0
  - qt-main=5.15.2=he8e5bd7_8
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtconsole=5.4.2=py38haa95532_0
  - qtpy=2.2.0=py38haa95532_0
  - qtwebkit=5.212=h2bbfb41_5
  - re2=2022.04.01=hd77b12b_0
  - requests=2.31.0=py38haa95532_0
  - requests-oauthlib=1.3.0=py_0
  - rfc3339-validator=0.1.4=py38haa95532_0
  - rfc3986-validator=0.1.1=py38haa95532_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.3.0=py38h4ed8f06_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py38haa95532_0
  - sip=6.6.2=py38hd77b12b_0
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.2.0=py38haa95532_1
  - soupsieve=2.4=py38haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tensorboard=2.10.0=py38haa95532_0
  - tensorboard-data-server=0.6.1=py38haa95532_0
  - tensorboard-plugin-wit=1.8.1=py38haa95532_0
  - tensorflow=2.10.0=mkl_py38ha5c4042_0
  - tensorflow-base=2.10.0=mkl_py38h6a7f48e_0
  - tensorflow-estimator=2.10.0=py38haa95532_0
  - terminado=0.17.1=py38haa95532_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py38haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38haa95532_0
  - tornado=6.3.2=py38h2bbff1b_0
  - traitlets=5.7.1=py38haa95532_0
  - ucrt=10.0.20348.0=haa95532_0
  - urllib3=1.26.16=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38haa95532_4
  - werkzeug=2.2.3=py38haa95532_0
  - wheel=0.38.4=py38haa95532_0
  - widgetsnbextension=4.0.5=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.2=h8cc25b3_0
  - y-py=0.5.9=py38hb6bf4ef_0
  - yaml=0.2.5=he774522_0
  - yarl=1.8.1=py38h2bbff1b_0
  - ypy-websocket=0.8.2=py38haa95532_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
    - absl-py==0.15.0
    - accelerate==0.29.3
    - addict==2.4.0
    - ants==0.0.7
    - antspyx==0.3.8
    - asgiref==3.7.2
    - backports-zoneinfo==0.2.1
    - boto3==1.34.36
    - botocore==1.34.36
    - certifi==2023.7.22
    - chardet==4.0.0
    - chart-studio==1.1.0
    - clang==5.0
    - comet-ml==3.33.10
    - commonmark==0.9.1
    - configobj==5.0.8
    - cupy-cuda11x==12.2.0
    - cycler==0.10.0
    - datasets==2.19.0
    - dill==0.3.8
    - django==4.2.7
    - dulwich==0.21.6
    - einops==0.8.0
    - et-xmlfile==2.0.0
    - everett==3.1.0
    - facexlib==0.3.0
    - fastmri==0.3.0
    - fastrlock==0.8.2
    - filelock==3.13.1
    - filterpy==1.4.5
    - fire==0.5.0
    - flatbuffers==1.12
    - fsspec==2024.2.0
    - ftfy==6.2.3
    - future==1.0.0
    - gevent==23.9.1
    - gitdb==4.0.10
    - gitpython==3.1.37
    - greenlet==3.0.1
    - h5py==2.10.0
    - huggingface-hub==0.22.2
    - icecream==2.1.3
    - idna==2.10
    - imageio==2.31.4
    - imgaug==0.4.0
    - importlib-metadata==8.5.0
    - itk-core==5.3.0
    - itk-io==5.3.0
    - itk-ioscanco==0.10.0
    - jmespath==1.0.1
    - keras==2.6.0
    - lazy-loader==0.3
    - lightning-utilities==0.11.7
    - llvmlite==0.41.1
    - lmdb==1.5.1
    - lpips==0.1.4
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - medpy==0.4.0
    - mpmath==1.3.0
    - multiprocess==0.70.16
    - networkx==3.1
    - nibabel==5.1.0
    - norfair==2.2.0
    - numba==0.58.1
    - numpy==1.23.3
    - openai-clip==1.0.1
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.8.0.74
    - openpyxl==3.1.5
    - pandas==2.0.3
    - patsy==0.5.3
    - pillow==10.0.1
    - piq==0.8.0
    - plotly==5.17.0
    - protobuf==3.19.6
    - py-cpuinfo==9.0.0
    - pyarrow==16.0.0
    - pyarrow-hotfix==0.6
    - pybboxes==0.1.6
    - pydicom==2.4.4
    - pygrappa==0.26.1
    - pyiqa==0.1.12
    - pymsgbox==1.0.9
    - python-box==6.1.0
    - python-dotenv==1.0.1
    - python-magic==0.4.27
    - pytorch-fid==0.3.0
    - pytorch-lightning==2.4.0
    - pytorch-msssim==1.0.0
    - pywavelets==1.4.1
    - regex==2023.12.25
    - requests-toolbelt==1.0.0
    - retrying==1.3.4
    - rich==12.6.0
    - roboflow==1.1.19
    - runstats==2.0.0
    - s3transfer==0.10.0
    - safetensors==0.4.2
    - sahi==0.11.15
    - scikit-image==0.21.0
    - scipy==1.10.0
    - seaborn==0.12.2
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - sentry-sdk==1.31.0
    - shapely==2.0.2
    - sigpy==0.1.16
    - simpleitk==2.3.0
    - simplejson==3.19.1
    - six==1.15.0
    - smmap==5.0.1
    - sqlparse==0.4.4
    - statsmodels==0.14.0
    - supervision==0.18.0
    - sympy==1.13.1
    - tenacity==8.2.3
    - tensorboardx==2.1
    - termcolor==1.1.0
    - terminaltables==3.1.10
    - thop==0.1.1-2209072238
    - tifffile==2023.7.10
    - timm==1.0.9
    - tokenizers==0.15.2
    - torch==2.4.0+cu118
    - torchaudio==2.4.0+cu118
    - torchmetrics==1.4.2
    - torchsummary==1.5.1
    - torchvision==0.19.0+cu118
    - tqdm==4.66.1
    - transformers==4.37.2
    - tsp-solver2==0.3
    - twixtools==1.0
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - ultralytics==8.0.188
    - wcwidth==0.2.13
    - webcolors==1.13
    - wget==3.2
    - wrapt==1.12.1
    - wurlitzer==3.0.3
    - xxhash==3.4.1
    - yapf==0.40.2
    - yolov5==7.0.13
    - zenodo-get==1.5.1
    - zipp==3.20.2
    - zope-event==5.0
    - zope-interface==6.1
prefix: C:\Users\fsadik\Anaconda3\envs\tensorflow_gpu
